In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import json
import requests

**Modifiers**
- `?expand=team.roster` Shows roster of active players for the specified team
- `?expand=person.names` Same as above, but gives less info.
- `?expand=team.schedule.next` Returns details of the upcoming game for a team
- `?expand=team.schedule.previous` Same as above but for the last game played
- `?expand=team.stats` Returns the teams stats for the season
- `?expand=team.roster&season=20142015` Adding the season identifier shows the roster for that season
- `?teamId=4,5,29` Can string team id together to get multiple teams
- `?stats=statsSingleSeasonPlayoffs` Specify which stats to get. Not fully sure all of the values

In [2]:
year1=1917
year2=1918

In [3]:
# Create url for API call.
teams_url = 'https://statsapi.web.nhl.com/api/v1/teams?expand=team.roster&season={}{}'.format(year1,year2)

In [4]:
teams_url

'https://statsapi.web.nhl.com/api/v1/teams?expand=team.roster&season=19171918'

In [5]:
# Submit request
# This returns resposne object
requests.get(teams_url)

In [6]:
res=requests.get(teams_url)

1 table for each team, for each year.
column headers to be:
- team ID
- team name
- location
- player ID
- player name

In [10]:
# res.json()['teams'][0]

Create on table containing each teams roster for each NHL season.

In [8]:
seasons = []
team_ids = []
team_names = []
player_ids = []
player_names = []

year1=1917
year2=1918

while year2 < 2023:
    try:
        teams_url = 'https://statsapi.web.nhl.com/api/v1/teams?expand=team.roster&season={}{}'.format(year1,year2)
        res=requests.get(teams_url)
        for i in res.json()['teams']:
            team_id = i['id']
            team_name = i['franchise']['teamName']
            for j in i['roster']['roster']:
                seasons.append(f'{year1}-{year2}')
                team_ids.append(team_id)
                team_names.append(team_name)
                player_ids.append(j['person']['id'])
                player_names.append(j['person']['fullName'])
    except:
        pass
    year1+=1
    year2+=1
# print(team_ids, team_names, player_ids, player_names)

In [9]:
rosters_df = pd.DataFrame({'season':seasons, 'team_ids':team_ids, 'team_names':team_names, 'player_ids':player_ids, 'player_names':player_names})
rosters_df

          season  team_ids team_names  player_ids    player_names
0      1917-1918        36     Eagles     8445135  George Boucher
1      1917-1918        36     Eagles     8445191    Morley Bruce
2      1917-1918        36     Eagles     8445802  Rusty Crawford
3      1917-1918        36     Eagles     8445844    Jack Darragh
4      1917-1918        36     Eagles     8445874      Cy Denneny
...          ...       ...        ...         ...             ...
52600  2021-2022        55     Kraken     8478468   Jeremy Lauzon
52601  2021-2022        55     Kraken     8478840     Will Borgen
52602  2021-2022        55     Kraken     8478891  Mason Appleton
52603  2021-2022        55     Kraken     8479987   Morgan Geekie
52604  2021-2022        55     Kraken     8480384  Alexander True

[52605 rows x 5 columns]

In [30]:
player_ids = []
player_names = []
player_birthdays = []
player_birthcities = []
player_nationalities = []
player_heights = []
player_weights = []
player_handedness = []
player_positions = []


for i in rosters_df['player_ids'].unique():
    players_url = 'https://statsapi.web.nhl.com/api/v1/people/{}'.format(i)
    res = requests.get(players_url).json()
#     try:
#         player_ids.append(res['people'][0]['id'])
#     except:
#         player_ids.append('NA')
#     try:
    player_names.append(res['people'][0]['fullName'])
#     except:
#         player_names.append('NA')
#     try:
#         player_birthdays.append(res['people'][0]['birthDate'])
#     except:
#         player_birthdays.append('NA')
#     try:
#         player_birthcities.append(res['people'][0]['birthCity'])
#     except:
#         player_birthcities.append('NA')
#     try:
#         player_nationalities.append(res['people'][0]['nationality'])
#     except:
#         player_nationalities.append('NA')
#     try:
#         player_heights.append(res['people'][0]['height'])
#     except:
#         player_heights.append('NA')
#     try:
#         player_weights.append(res['people'][0]['weight'])
#     except:
#         player_weights.append('NA')
#     try:
#         player_handedness.append(res['people'][0]['shootsCatches'])
#     except:
#         player_handedness.append('NA')
#     try:
#         player_positions.append(res['people'][0]['primaryPosition']['name'])
#     except:
#         player_positions.append('NA')

In [31]:
player_ids = []
player_names = []
player_birthdays = []
player_birthcities = []
player_birthcountries = []
player_nationalities = []
player_heights = []
player_weights = []
player_handedness = []
player_positions = []


for i in rosters_df['player_ids'].unique():
    players_url = 'https://statsapi.web.nhl.com/api/v1/people/{}'.format(i)
    res = requests.get(players_url).json()
    try:
        player_ids.append(res['people'][0]['id'])
    except:
        player_ids.append('NA')
    try:
        player_names.append(res['people'][0]['fullName'])
    except:
        player_names.append('NA')
    try:
        player_birthdays.append(res['people'][0]['birthDate'])
    except:
        player_birthdays.append('NA')
    try:
        player_birthcities.append(res['people'][0]['birthCity'])
    except:
        player_birthcities.append('NA')
    try:
        player_birthcountries.append(res['people'][0]['birthCountry'])
    except:
        player_birthcountries.append('NA')
    try:
        player_nationalities.append(res['people'][0]['nationality'])
    except:
        player_nationalities.append('NA')
    try:
        player_heights.append(res['people'][0]['height'])
    except:
        player_heights.append('NA')
    try:
        player_weights.append(res['people'][0]['weight'])
    except:
        player_weights.append('NA')
    try:
        player_handedness.append(res['people'][0]['shootsCatches'])
    except:
        player_handedness.append('NA')
    try:
        player_positions.append(res['people'][0]['primaryPosition']['name'])
    except:
        player_positions.append('NA')

In [33]:
players_df = pd.DataFrame({
    'player_ids': player_ids,
    'player_names': player_names,
    'player_birthdays': player_birthdays,
    'player_birthcities': player_birthcities,
    'player_birthcountries': player_birthcountries,
    'player_nationalities': player_nationalities,
    'player_heights': player_heights,
    'player_weights': player_weights,
    'player_handedness': player_handedness,
    'player_positions': player_positions
})
players_df

,player_ids,player_names,player_birthdays,player_birthcities,player_birthcountries,player_nationalities,player_heights,player_weights,player_handedness,player_positions
0,8445135,George Boucher,1896-08-19,Ottawa,CAN,CAN,"5' 9""",169,L,Defenseman
1,8445191,Morley Bruce,1894-03-07,North Gower,CAN,CAN,"5' 9""",170,R,Defenseman
2,8445802,Rusty Crawford,1885-11-07,Cardinal,CAN,CAN,"5' 11""",165,L,Left Wing
3,8445844,Jack Darragh,1890-12-04,Ottawa,CAN,CAN,"5' 10""",168,R,Right Wing
4,8445874,Cy Denneny,1891-12-23,Farran's Point,CAN,CAN,"5' 7""",168,L,Left Wing
...,...,...,...,...,...,...,...,...,...,...
8201,8480049,Dylan Samberg,1999-01-24,Saginaw,USA,USA,"6' 3""",190,L,Defenseman
8202,8478062,Dysin Mayo,1996-08-17,Victoria,CAN,CAN,"6' 2""",195,R,Defenseman
8203,8478872,Karel Vejmelka,1996-05-25,Trebic,CZE,CZE,"6' 3""",224,R,Goalie
8204,8479341,Cam Dineen,1998-06-19,Toms River,USA,USA,"5' 11""",183,L,Defenseman
8205,8482655,Janis Moser,2000-06-06,Biel,CHE,CHE,"6' 1""",172,L,Defenseman

In [54]:
# players_df.to_csv('../data/players_df.csv')

In [55]:
# rosters_df.to_csv('../data/rosters_df.csv')

In [2]:
# players_df.sort_values('player_birthdays', inplace=True)
# plt.bar(players_df['player_birthdays'], players_df['player_heights'])

In [51]:
# rosters_df.join(players_df, lsuffix='_fromRoster', rsuffix='_fromPlayers',on='player_ids', how='outer')

In [ ]:
# {'id': 8471214,
#  'fullName': 'Alex Ovechkin',
#  'link': '/api/v1/people/8471214',
#  'firstName': 'Alex',
#  'lastName': 'Ovechkin',
#  'primaryNumber': '8',
#  'birthDate': '1985-09-17',
#  'currentAge': 36,
#  'birthCity': 'Moscow',
#  'birthCountry': 'RUS',
#  'nationality': 'RUS',
#  'height': '6\' 3"',
#  'weight': 238,
#  'active': True,
#  'alternateCaptain': False,
#  'captain': True,
#  'rookie': False,
#  'shootsCatches': 'R',
#  'rosterStatus': 'Y',
#  'currentTeam': {'id': 15,
#   'name': 'Washington Capitals',
#   'link': '/api/v1/teams/15'},
#  'primaryPosition': {'code': 'L',
#   'name': 'Left Wing',
#   'type': 'Forward',
#   'abbreviation': 'LW'}}

In [4]:
# players_url = 'https://statsapi.web.nhl.com/api/v1/people/8445135'
# res = requests.get(players_url).json()
# res['people'][0]['primaryPosition']